
spring.security.oauth2.client:
  registration:
    google:
      client-id: 1086178295787-fvbnm9glnvh3ncdajdkauenh6v0j7c58.apps.googleusercontent.com
      client-secret: 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
      scope: profile,email

    kakao:
      client-id: 66f29ca70216a0aa2eae72f13f90a74f
      client-secret: VS9HmSJN3F9nRCW3rqUoHZ86CnhwYDMj
      redirect-uri: http://192.168.45.96:8080/login/oauth2/code/kakao
      client-authentication-method: client_secret_post
      authorization-grant-type: authorization_code
      scope: profile_nickname
      client-name: Kakao

    naver:
      client-id: Omd0phxBSwoSkmmRVCOl
      client-secret: RQE4BFtbJk
      redirect-uri: http://192.168.45.96:8080/login/oauth2/code/naver
      client-authentication-method: client_secret_post
      authorization-grant-type: authorization_code
      scope: name,email,profile_image
      client-name: Naver

  provider:
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: response

    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id


