spring:
  profiles:
    active: local
    include: oauth
  datasource:
    url: jdbc:h2:tcp://192.168.45.96/~/ggudok;IGNORECASE=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
  web:
    resources:
      static-locations: classpath:static/images/,classpath:/META-INF/,classpath:/static/

server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.hibernate.SQL: debug
 #   org.hibernate.orm.jdbc.bind: trace

upload:
  subs:
    main: C:/ggudown/subs/main/
    icon: C:/ggudown/subs/icon/
  category: C:/ggudown/category/
  member: C:/ggudown/member/
  event: C:/ggudown/event/

download:
  subs:
    main: /images/subs/main/
    icon: /images/subs/icon/
  category: /images/category/
  member: /images/member/
  event: /images/event/

jwt:
  secretKey: ggudok
  expiration: 30
  header: access
  refresh:
    expiration: 30
    header: refresh


